#!/bin/sh -e

export PATH="bin:$PATH"

build_opts="prefix=/usr \
  bindir=/usr/bin \
  sysconfdir=/etc \
  MARCH=x86-64"


git submodule init
git submodule update

make release VERBOSE=1 JLDFLAGS=${LDFLAGS} $build_opts
make DESTDIR="$1" install VERBOSE=1 $build_opts
