#!/bin/sh -e

export PATH="bin:$PATH"

git submodule init
git submodule update

make release VERBOSE=1 JLDFLAGS="${LDFLAGS}" \
  prefix=/usr \
  bindir=/usr/bin \
  sysconfdir=/etc \
  MARCH=x86-64

make DESTDIR="$1" install VERBOSE=1 \
  prefix=/usr \
  bindir=/usr/bin \
  sysconfdir=/etc \
  MARCH=x86-64
