#!/bin/sh -e

printf "+-----------------------------------------------------+
| ATTENTION                                02/04/2021 |
+-----------------------------------------------------+
| All packages have been updated except for a few     |
| that require additional work to get them fully      |
| functional                                          |
| I will fix it but till then don't, just don't.      |
|                                                     |
|  [x] zig                                            |
|                                                     |
|                                                     |
|                                                     |
|                                                     |
+-----------------------------------------------------+\n"

