#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DD_COMPILER='/usr/bin/gdmd'

make -C build

cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=True \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DD_COMPILER=build/bin/ldmd2 

make

cmake --install build
