#!/bin/sh -e

unset AR NM CC CXX RANLIB DESTDIR

TARGET="x86_64-linux-musl"
MCPU="native"

./build -j"$(nproc)" "$TARGET" "$MCPU"

mkdir -p "$1/usr/bin"
cp    "out/zig-${TARGET}-${MCPU}/bin/zig" "$1/usr/bin/zig"
cp -r "out/zig-${TARGET}-${MCPU}/lib"     "$1/usr"
