#!/bin/sh -e

echo $2
echo $1

for patch in *.patch; do
    patch -p1 < "$patch"
done

git describe --long --tags 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"


export PATH="core/bin:$PATH"
export CRYSTAL_CONFIG_VERSION="0.35.1"
export EXPORT_CC="CC=cc"

make release=1 FLAGS="--no-debug" \
    CRYSTAL_PATH="src" \
    CRYSTAL_CONFIG_PATH="/usr/lib/crystal" \
    CRYSTAL_CACHE_DIR=".tmp/crystal"
    LLVM_CONFIG="/usr/bin/llvm-config"


install -Dm755 .build/crystal "$1/usr/bin/crystal"
install -Dm755 "$1/usr/lib"

cp -a src "$1/usr/lib/crystal"

install -Dm644 etc/completion.bash "$1r/usr/share/bash-completion/completions/crystal"
install -Dm644 etc/completion.zsh "$1/usr/share/zsh/site-functions/_crystal"
