#!/bin/sh -e

export AS="cc -c"
export ASPP="cc -c"

for patch in *.patch; do
    patch -p1 < "$patch"
done

./configure \
	--prefix /usr \
	--bindir /usr/bin \
	--libdir /usr/lib/ocaml \
	--mandir /usr/share/man \
    --disable-force-safe-string \

make world.opt
make DESTDIR="$1" install

install -Dm644 LICENSE "$1/usr/share/licenses/ocaml/LICENSE"

# To be consistent with other binaries.
mv "$1/usr/bin/ocamldoc" "$1/usr/bin/ocamldoc.byte"
ln -s ocamldoc.opt "$1/usr/bin/ocamldoc"

# We can save some space by removing a few unnecessary files.
find "$1/usr/lib" \
    -type f -name '*.so.*' -exec strip --strip-unneeded {} \;
# Remove annotation files and sources.
find "$1/usr/lib/ocaml" \
	\( -name '*.cmt' -o -name '*.cmti' -o -name '*.ml' \) \
	-a -delete

for i in \
	'*.cmo' \
	'*.cmi' \
	'*.cma' \
	'VERSION' \
	'stublibs' \
	'vmthreads/*.cmi' \
	'vmthreads/*.cma' \
	'threads/*.cmi' \
	'threads/*.cma'
do
	rm -rf "$1/usr/lib/ocaml/$i"
done

rm -rf "$1/usr/lib/ocaml/compiler-libs"
