#!/bin/sh -e

export VFLAGS='-cc gcc'

make

mkdir -p "$1/usr/lib/vlang"
mkdir -p "$1/usr/share/vlang"
mkdir -p "$1/usr/bin"

install -Dm755 v "$1/usr/lib/vlang/v"

cp -r cmd "$1/usr/lib/vlang/"
cp -r examples "$1/usr/share/vlang/"
cp -r thirdparty "$1/usr/lib/vlang/"
cp -r vlib "$1/usr/lib/vlang/"

cp v.mod "$1/usr/lib/vlang/"

# I have mixed feelings about this.
#chmod 777 "$1/usr/lib/vlang/cmd/tools"

ln -s /usr/lib/vlang/v "$1/usr/bin/v"
