#!/bin/sh -e

cat <<EOF	
NOTE: To enable 'java' add this to your	
      '.shellrc' or '.profile'.

-> export JAVA_HOME=$JAVA_HOME:/usr/lib/jvm/openjdk-jre8"
    
-> Add '/usr/lib/jvm/openjdk-jre8/bin' to your 'PATH'

NOTE: The that this is not a native build.	
      Please report all bugs and errors.		
EOF
