#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

export CFLAGS="${CFLAGS} -fno-omit-frame-pointer"

make

install -Dm755 execinfo.h  "$1/usr/include/execinfo.h"
install -Dm755 stacktraverse.h  "$1/usr/include/stacktraverse.h"
install -Dm755 libexecinfo.a  "$1/usr/lib/libexecinfo.a"
install -Dm755 libexecinfo.so.1 "$1/usr/lib/libexecinfo.so.1"
ln -s libexecinfo.so.1 "$1/usr/lib/libexecinfo.so"
