#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

mv "dmd-config.conf" "dmd.conf"

mkdir -p install

make -C "dmd/" -f posix.mak HOST_DMD=ldmd2 ENABLE_RELEASE=1 INSTALL_DIR="install" install
make -C "druntime/" -f posix.mak ENABLE_RELEASE=1 INSTALL_DIR="install" install
make -C "phobos/" -f posix.mak ENABLE_RELEASE=1 INSTALL_DIR="install" install

mkdir -p "$1/usr/bin/" 
mkdir -p "$1/usr/lib/" 
mkdir -p "$1/etc/" 
mkdir -p "$1/usr/include/d/"

install -Dm644 dmd.conf "$1/etc/dmd.conf"
install -Dm755 dmd/generated/linux/release/64/dmd "$1/usr/bin/dmd"

mkdir -p "$1/usr/include/dlang/dmd/"

cp -r dmd/generated/linux/release/64/* "$1/usr/lib/"
cp -r druntime/import/* "$1/usr/include/dlang/dmd/"
cp -r phobos/std "$1/usr/include/dlang/dmd/"
cp -r phobos/etc "$1/usr/include/dlang/dmd/"
cp -r phobos/*.d "$1/usr/include/dlang/dmd/"

# This entire section is messy, I don't know much shell so this is
# very hacky but it works so for now it'll do the job.
find druntime/ -name "*.a*" -exec cp -r {} "$1/usr/lib/" +
find phobos/ -name "*.a*" -exec cp -r {} "$1/usr/lib/" +
find dmd/generated/linux/release/ -name "*.a*" -exec cp -r {} "$1/usr/lib/" +
find druntime/ -name "*.a" -exec cp -r {} "$1/usr/lib/" +
find phobos/ -name "*.a" -exec cp -r {} "$1/usr/lib/" +
find dmd/generated/linux/release/ -name "*.a" -exec cp -r {} "$1/usr/lib/" +
find druntime/ -name "*.so.a" -exec cp -r {} "$1/usr/lib/" +
find phobos/ -name "*.so.a" -exec cp -r {} "$1/usr/lib/" +
find dmd/generated/linux/release/ -name "*.so.a" -exec cp -r {} "$1/usr/lib/" +
find druntime/ -name "*.so*" -exec cp -r {} "$1/usr/lib/" +
find phobos/ -name "*.so*" -exec cp -r {} "$1/usr/lib/" +
find dmd/generated/linux/release/ -name "*.so*" -exec cp -r {} "$1/usr/lib/" +
find druntime/ -name "*.o" -exec cp -r {} "$1/usr/lib/" +
find phobos/ -name "*.o" -exec cp -r {} "$1/usr/lib/" +
find dmd/generated/linux/release/ -name "*.o" -exec cp -r {} "$1/usr/lib/" +

rm "$1/usr/lib/dmd"
