#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

export CFLAGS="$CFLAGS -fno-strict-aliasing"

./autogen.sh \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --disable-rpath \
    --disable-boehm \
    --enable-parallel-mark \
    --with-mcs-docs=no \
    --without-sigaltstack

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/*.la"
rm -rf "$1/usr/lib/mono/*/Mono.Security.Win32*"
rm -rf "$1/usr/lib/libMonoSupportW.*"
